// This file is automatically generated. Do not modify it manually.

// IMPORTANT: This configuration is for client-side use only. Do not expose sensitive credentials.
// This is a placeholder configuration. Replace with your actual Firebase project configuration.
export const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};
